version: '3.8'
services:
  php-fpm:
    # sesuaikan php ini
    image: tongkolspace/php-fpm:8.1-v1.0.1
    container_name: php-fpm-wordpress-${APP_NAME}
    restart: unless-stopped
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      TZ: ${TZ}
    volumes:
      - ../wordpress:/var/www/html/
      - ./php-fpm/php-dev.ini:/usr/local/etc/php/conf.d/zz-custom-php.ini
      - ./php-fpm/php-fpm-dev.conf:/usr/local/etc/php-fpm.d/easyengine.conf  
    networks:
      - external
      - internal
  nginx:
    image: tongkolspace/nginx-ee:v1.0.2
    container_name: nginx-wordpress-${APP_NAME}
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ../wordpress:/var/www/html
      - ../admin:/var/www/admin
      - ./nginx/sites-enabled/admin-dev.conf:/etc/nginx/sites-enabled/admin.conf
      - ./nginx/sites-enabled/wordpress.conf:/etc/nginx/sites-enabled/default
      - ./nginx/log:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/common-extra:/etc/nginx/common-extra
      - ./nginx/conf.d-extra:/etc/nginx/conf.d-extra
      - ./nginx/conf.d/cloudflare.conf:/etc/nginx/conf.d/cloudflare.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/tmp/nginx:/tmp/nginx
    depends_on:
      - redis
    networks:
      - external
      - internal
    environment:
      TZ: ${TZ}
    ports:
      - 80:80
      - 57710:57710
  redis:
    image: redis:latest
    container_name: redis-wordpress-${APP_NAME}
    restart: unless-stopped
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      TZ: ${TZ}
    networks:
      - internal
  workspace-wordpress:
    image: tongkolspace/workspace:8.1-v1.0.1
    container_name: workspace-wordpress-${APP_NAME}
    build:
      context: ./workspace
      dockerfile: Dockerfile
    volumes:
      - ./php-fpm/php-dev.ini:/usr/local/etc/php/conf.d/zz-custom-php.ini
      - ../wordpress:/var/www/html
    env_file:
      - .env
    environment:
      TZ: "${TZ}"
    networks:
      - internal
      - external
    ports:
      # Bakend Laravel
      - 8000:8000
      - 5173:5173
  db:
    image: mariadb:11.3.2
    container_name: db-wordpress-${APP_NAME}
    restart: unless-stopped
    # ports:
    # Uncomment jika tidak ingin ekpsose
    # - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}       
      MYSQL_USER: "${DB_USERNAME}"               
      MYSQL_PASSWORD: "${DB_PASSWORD}"       
      TZ: ${TZ}
    volumes:
      - ./mysql/config/mysql-dev.cnf:/etc/my.cnf
      - ./mysql/datadir:/var/lib/mysql
    networks:
      - external
      - internal
  pma:
    # Akses dengan http://domain/pma/ (wajib dengan slash)
    image: phpmyadmin/phpmyadmin
    container_name: pma-wordpress-${APP_NAME}
    restart: unless-stopped
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      UPLOAD_LIMIT: 50M
      PMA_ABSOLUTE_URI: "http://${DOMAIN_WORDPRESS}/pma/"
    links:
      - db:db
    networks:
      - internal
  redis-commander:
    container_name: redis-commander-wordpress-${APP_NAME}
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: unless-stopped
    environment:
    - REDIS_HOSTS=local:redis:6379
    networks:
      - internal
networks:
  external:
    external: true
    name: ${NETWORK}
  internal:
