services:
  wordpress:
    image: app-wordpress-${APP_NAME}:${APP_TAG} 
    ports: !reset 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress-${APP_NAME}.tls=true"
      - "traefik.http.routers.wordpress-${APP_NAME}.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.http.routers.wordpress-${APP_NAME}.rule=Host(`${DOMAIN_WORDPRESS}`)"
      - "traefik.http.routers.wordpress-${APP_NAME}.entrypoints=web,websecure"
      - "traefik.http.routers.wordpress-${APP_NAME}.service=wordpress-${APP_NAME}"
      - "traefik.http.services.wordpress-${APP_NAME}.loadbalancer.server.port=80"
      - "traefik.http.routers.wordpress-admin-${APP_NAME}.tls=true"
      - "traefik.http.routers.wordpress-admin-${APP_NAME}.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.http.routers.wordpress-admin-${APP_NAME}.rule=Host(`${DOMAIN_WORDPRESS}`)"
      - "traefik.http.routers.wordpress-admin-${APP_NAME}.entrypoints=admin"
      - "traefik.http.routers.wordpress-admin-${APP_NAME}.service=wordpress-admin-${APP_NAME}"
      - "traefik.http.services.wordpress-admin-${APP_NAME}.loadbalancer.server.port=57710"
      - "traefik.docker.network=${NETWORK}"

