version: '3.8'
services:
  traefik:
    image: traefik:latest
    container_name: reverse-proxy-${APP_NAME}
    restart: unless-stopped
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard-${APP_NAME}.tls=true"
      - "traefik.http.routers.traefik-dashboard-${APP_NAME}.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.http.routers.traefik-dashboard-${APP_NAME}.rule=Host(`${DOMAIN_PROXY}`)"
      - "traefik.http.routers.traefik-dashboard-${APP_NAME}.entrypoints=traefik-dashboard"
      - "traefik.http.routers.traefik-dashboard-${APP_NAME}.service=api@internal"
      # global redirect to https
      - "traefik.http.routers.http-catchall-${APP_NAME}.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall-${APP_NAME}.entrypoints=web,admin"
      - "traefik.http.routers.http-catchall-${APP_NAME}.middlewares=redirect-to-https-${APP_NAME}"
      # # middleware redirect
      - "traefik.http.middlewares.redirect-to-https-${APP_NAME}.redirectscheme.scheme=https"
    ports:
      - "80:80" 
      - "443:443"
      - "57710:57710"
      # Debugging
      # - "57711:57711"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/logs:/logs/
      - ./traefik/certs:/certs/
      - acme:/acme/
    networks:
      - external
  nginx-traefik:
    image: tongkolspace/nginx-ee:v1.0.2
    container_name: nginx-traefik-admin-${APP_NAME}
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/empty:/var/www/html
      - ../admin/index-traefik.html:/var/www/admin/index.html
      # - ./nginx/sites-enabled/backend.conf:/etc/nginx/sites-enabled/default
      - ./nginx/sites-enabled/admin-traefik.conf:/etc/nginx/sites-enabled/admin.conf
      - ./nginx/log:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/empty:/etc/nginx/conf-extra
      - ./nginx/common-extra:/etc/nginx/common-extra
      # - ./nginx/conf.d/cloudflare.conf:/etc/nginx/conf.d/cloudflare.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-admin-${APP_NAME}.tls=true"
      - "traefik.http.routers.traefik-admin-${APP_NAME}.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.http.routers.traefik-admin-${APP_NAME}.rule=Host(`${DOMAIN_PROXY}`)"
      - "traefik.http.routers.traefik-admin-${APP_NAME}.entrypoints=admin"
      - "traefik.http.routers.traefik-admin-${APP_NAME}.service=traefik-admin-${APP_NAME}"
      - "traefik.http.services.traefik-admin-${APP_NAME}.loadbalancer.server.port=57710"
      - "traefik.docker.network=${NETWORK}"
    networks:
      - internal
      - external
    depends_on:
      - traefik
    environment:
      TZ: ${TZ}
networks:
  internal:
    name: ${APP_NAME}-${NETWORK}
  external:
    external: true
    name: ${NETWORK}

volumes:
   acme:
